# -*- coding: utf-8 -*-
"""BCGXGenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10K4CxYTZpev5s4ujVOQBid4l8iXE2E92
"""

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/10K.csv')

# Sort the data by Company and Year for accurate percentage change calculations
df = df.sort_values(by=['Company', 'Year'])

# Calculate Revenue Growth %
df['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue'].pct_change() * 100

# Calculate Net Income Growth %
df['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income'].pct_change() * 100

# Calculate Total Assets Growth %
df['Assets Growth (%)'] = df.groupby(['Company'])['Total Assets'].pct_change() * 100

# Calculate Total Liabilities Growth %
df['Liabilities Growth (%)'] = df.groupby(['Company'])['Total Liabilities'].pct_change() * 100

# Calculate Operating Cash Flow Growth %
df['Cash Flow Growth (%)'] = df.groupby(['Company'])['Cash Flow from Operating Activities'].pct_change() * 100

# Display the updated DataFrame
df

# Average financial metrics per company across all years
avg_by_company = df.groupby('Company')[[
    'Total Revenue', 'Net Income', 'Total Assets',
    'Total Liabilities', 'Cash Flow from Operating Activities'
]].mean().round(2)

avg_by_company

# Max values per company
max_by_company = df.groupby('Company')[[
    'Total Revenue', 'Net Income', 'Total Assets',
    'Total Liabilities', 'Cash Flow from Operating Activities'
]].max()

# Min values per company
min_by_company = df.groupby('Company')[[
    'Total Revenue', 'Net Income', 'Total Assets',
    'Total Liabilities', 'Cash Flow from Operating Activities'
]].min()

max_by_company

min_by_company

# Total revenue per year across companies
total_revenue_by_year = df.groupby('Year')['Total Revenue'].sum()

total_revenue_by_year

# Revenue share each company contributes in each year
revenue_share = df.pivot_table(
    values='Total Revenue',
    index='Year',
    columns='Company',
    aggfunc='sum'
)

# Convert to % share per year
revenue_share_pct = revenue_share.div(revenue_share.sum(axis=1), axis=0) * 100
revenue_share_pct.round(2)

df.to_csv('Processed_Financials.csv', index=False)

## Summary of Financial Findings (Microsoft, Apple, Tesla – 10-K Analysis)

### Overview
# We analyzed the last three fiscal years (2022–2024) of 10-K filings for Microsoft, Apple, and Tesla. Key financial metrics examined included:

#- Total Revenue
#- Net Income
#- Total Assets
#- Total Liabilities
#- Cash Flow from Operating Activities

#Using Python and pandas, we calculated year-over-year percentage changes and explored aggregate trends across companies and years to support the foundation of an AI-powered financial assistant.


### Company-wise Trends

#### Microsoft
#- Total Revenue grew consistently, rising from $198,270M (2022) to $245,122M (2024), reflecting robust business expansion.
#- Net Income increased significantly, indicating high profitability and operational leverage.
#- Operating Cash Flow exceeded $118,548M in 2024, showing excellent internal capital generation.
#- Assets and liabilities both expanded, maintaining a healthy financial balance.

#### Apple
#- Revenue showed steady growth from $383,285M (2023) to $391,035M (2024), with only slight annual increases.
#- Net Income declined in 2024 after peaking at $96,995M in 2023, suggesting margin pressures or rising costs.
#- Operating Cash Flow remained strong and stable around $118,254M.
#- Liabilities and Assets rose gradually, consistent with business scale and investment cycles.

#### Tesla
#- Revenue grew from $81,462M (2022) to $97,690M (2024), but growth slowed in the most recent year.
#- Net Income jumped from $12,587M (2022) to $14,974M (2023) but sharply dropped to $7,153M in 2024, signaling volatility in profitability.
#- Cash Flow from Operations remained relatively flat, with a minor rise to $14,923M in 2024.
#- Assets and Liabilities increased year-over-year, with a notable asset build-up in 2024.


### Aggregated Insights

#- Microsoft had the highest average Net Income and Operating Cash Flow, signaling mature, consistent performance.
#- Apple led in Total Revenue and maintained efficient operations with strong free cash flows.
#- Tesla experienced volatile earnings, with signs of risk due to sharp swings in profitability despite asset growth.
#- Total revenue across all companies rose year-over-year, with Microsoft and Apple dominating the revenue share.
#- A pivot analysis of revenue share showed Microsoft and Apple holding over 75–80% of the combined yearly revenue, while Tesla’s share remained smaller and more variable.



### AI-Driven Insight Opportunities

#- The structured patterns in Microsoft and Apple’s financials make them ideal for AI models focused on stability and trend forecasting.
#- Tesla’s fluctuations offer training material for anomaly detection or risk alerts in automated financial advisors.
#- The analysis supports building use cases for an AI chatbot to interpret earnings reports, flag growth patterns, or answer investor-style queries using company-specific financial trajectories.